# Tarpaulin configuration
[default]
workspace = true
engine = "Llvm"
all-features = true
exclude-files = ["gpg-inspector/tests/*", "gpg-inspector-lib/tests/*"]
output-dir = "coverage"
out = ["Lcov", "Html"]
